/*
 * Copyright (c) 2024 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package constant

import "time"

// Compatible with OBShell which version prior to 4.2.3
var OB_CONFIG_COMPATIBLE_MAP = map[string]string{
	CONFIG_RPC_PORT:   "rpcPort",
	CONFIG_MYSQL_PORT: "mysqlPort",
}

var OB_INNER_USERS = []string{"PUBLIC", "LBACSYS", "ORAAUDITOR", "__oceanbase_inner_standby_user", "ocp_monitor"}
var OB_NO_PRIVILEGE_DBS = []string{"information_schema"}
var OB_RESTRICTED_DBS = []string{"oceanbase", "mysql", "SYS", "LBACSYS", "ORAAUDITOR"}
var OB_EXCLUDED_USERS = []string{"PUBLIC", "LBACSYS", "ORAAUDITOR", "__oceanbase_inner_standby_user"}

const (
	OB_MYSQL_PRIVILEGE_ALTER          = "ALTER"
	OB_MYSQL_PRIVILEGE_CREATE         = "CREATE"
	OB_MYSQL_PRIVILEGE_DELETE         = "DELETE"
	OB_MYSQL_PRIVILEGE_DROP           = "DROP"
	OB_MYSQL_PRIVILEGE_INSERT         = "INSERT"
	OB_MYSQL_PRIVILEGE_SELECT         = "SELECT"
	OB_MYSQL_PRIVILEGE_UPDATE         = "UPDATE"
	OB_MYSQL_PRIVILEGE_INDEX          = "INDEX"
	OB_MYSQL_PRIVILEGE_CREATE_VIEW    = "CREATE_VIEW"
	OB_MYSQL_PRIVILEGE_SHOW_VIEW      = "SHOW_VIEW"
	OB_MYSQL_PRIVILEGE_CREATE_USER    = "CREATE_USER"
	OB_MYSQL_PRIVILEGE_PROCESS        = "PROCESS"
	OB_MYSQL_PRIVILEGE_SUPER          = "SUPER"
	OB_MYSQL_PRIVILEGE_SHOW_DATABASES = "SHOW_DATABASES"
	OB_MYSQL_PRIVILEGE_GRANT_OPTION   = "GRANT_OPTION"

	// Oracle privileges
	OB_ORACLE_PRIVILEGE_CREATE_SESSION              = "CREATE_SESSION"
	OB_ORACLE_PRIVILEGE_CREATE_TABLE                = "CREATE_TABLE"
	OB_ORACLE_PRIVILEGE_CREATE_ANY_TABLE            = "CREATE_ANY_TABLE"
	OB_ORACLE_PRIVILEGE_ALTER_ANY_TABLE             = "ALTER_ANY_TABLE"
	OB_ORACLE_PRIVILEGE_BACKUP_ANY_TABLE            = "BACKUP_ANY_TABLE"
	OB_ORACLE_PRIVILEGE_DROP_ANY_TABLE              = "DROP_ANY_TABLE"
	OB_ORACLE_PRIVILEGE_LOCK_ANY_TABLE              = "LOCK_ANY_TABLE"
	OB_ORACLE_PRIVILEGE_COMMENT_ANY_TABLE           = "COMMENT_ANY_TABLE"
	OB_ORACLE_PRIVILEGE_SELECT_ANY_TABLE            = "SELECT_ANY_TABLE"
	OB_ORACLE_PRIVILEGE_INSERT_ANY_TABLE            = "INSERT_ANY_TABLE"
	OB_ORACLE_PRIVILEGE_UPDATE_ANY_TABLE            = "UPDATE_ANY_TABLE"
	OB_ORACLE_PRIVILEGE_DELETE_ANY_TABLE            = "DELETE_ANY_TABLE"
	OB_ORACLE_PRIVILEGE_FLASHBACK_ANY_TABLE         = "FLASHBACK_ANY_TABLE"
	OB_ORACLE_PRIVILEGE_CREATE_ROLE                 = "CREATE_ROLE"
	OB_ORACLE_PRIVILEGE_DROP_ANY_ROLE               = "DROP_ANY_ROLE"
	OB_ORACLE_PRIVILEGE_GRANT_ANY_ROLE              = "GRANT_ANY_ROLE"
	OB_ORACLE_PRIVILEGE_ALTER_ANY_ROLE              = "ALTER_ANY_ROLE"
	OB_ORACLE_PRIVILEGE_AUDIT_ANY                   = "AUDIT_ANY"
	OB_ORACLE_PRIVILEGE_GRANT_ANY_PRIVILEGE         = "GRANT_ANY_PRIVILEGE"
	OB_ORACLE_PRIVILEGE_GRANT_ANY_OBJECT_PRIVILEGE  = "GRANT_ANY_OBJECT_PRIVILEGE"
	OB_ORACLE_PRIVILEGE_CREATE_ANY_INDEX            = "CREATE_ANY_INDEX"
	OB_ORACLE_PRIVILEGE_ALTER_ANY_INDEX             = "ALTER_ANY_INDEX"
	OB_ORACLE_PRIVILEGE_DROP_ANY_INDEX              = "DROP_ANY_INDEX"
	OB_ORACLE_PRIVILEGE_CREATE_ANY_VIEW             = "CREATE_ANY_VIEW"
	OB_ORACLE_PRIVILEGE_DROP_ANY_VIEW               = "DROP_ANY_VIEW"
	OB_ORACLE_PRIVILEGE_CREATE_VIEW                 = "CREATE_VIEW"
	OB_ORACLE_PRIVILEGE_SELECT_ANY_DICTIONARY       = "SELECT_ANY_DICTIONARY"
	OB_ORACLE_PRIVILEGE_CREATE_PROCEDURE            = "CREATE_PROCEDURE"
	OB_ORACLE_PRIVILEGE_CREATE_ANY_PROCEDURE        = "CREATE_ANY_PROCEDURE"
	OB_ORACLE_PRIVILEGE_ALTER_ANY_PROCEDURE         = "ALTER_ANY_PROCEDURE"
	OB_ORACLE_PRIVILEGE_DROP_ANY_PROCEDURE          = "DROP_ANY_PROCEDURE"
	OB_ORACLE_PRIVILEGE_EXECUTE_ANY_PROCEDURE       = "EXECUTE_ANY_PROCEDURE"
	OB_ORACLE_PRIVILEGE_CREATE_SYNONYM              = "CREATE_SYNONYM"
	OB_ORACLE_PRIVILEGE_CREATE_ANY_SYNONYM          = "CREATE_ANY_SYNONYM"
	OB_ORACLE_PRIVILEGE_DROP_ANY_SYNONYM            = "DROP_ANY_SYNONYM"
	OB_ORACLE_PRIVILEGE_CREATE_PUBLIC_SYNONYM       = "CREATE_PUBLIC_SYNONYM"
	OB_ORACLE_PRIVILEGE_DROP_PUBLIC_SYNONYM         = "DROP_PUBLIC_SYNONYM"
	OB_ORACLE_PRIVILEGE_CREATE_SEQUENCE             = "CREATE_SEQUENCE"
	OB_ORACLE_PRIVILEGE_CREATE_ANY_SEQUENCE         = "CREATE_ANY_SEQUENCE"
	OB_ORACLE_PRIVILEGE_ALTER_ANY_SEQUENCE          = "ALTER_ANY_SEQUENCE"
	OB_ORACLE_PRIVILEGE_DROP_ANY_SEQUENCE           = "DROP_ANY_SEQUENCE"
	OB_ORACLE_PRIVILEGE_SELECT_ANY_SEQUENCE         = "SELECT_ANY_SEQUENCE"
	OB_ORACLE_PRIVILEGE_CREATE_TRIGGER              = "CREATE_TRIGGER"
	OB_ORACLE_PRIVILEGE_CREATE_ANY_TRIGGER          = "CREATE_ANY_TRIGGER"
	OB_ORACLE_PRIVILEGE_ALTER_ANY_TRIGGER           = "ALTER_ANY_TRIGGER"
	OB_ORACLE_PRIVILEGE_DROP_ANY_TRIGGER            = "DROP_ANY_TRIGGER"
	OB_ORACLE_PRIVILEGE_CREATE_PROFILE              = "CREATE_PROFILE"
	OB_ORACLE_PRIVILEGE_ALTER_PROFILE               = "ALTER_PROFILE"
	OB_ORACLE_PRIVILEGE_DROP_PROFILE                = "DROP_PROFILE"
	OB_ORACLE_PRIVILEGE_CREATE_USER                 = "CREATE_USER"
	OB_ORACLE_PRIVILEGE_BECOME_USER                 = "BECOME_USER"
	OB_ORACLE_PRIVILEGE_ALTER_USER                  = "ALTER_USER"
	OB_ORACLE_PRIVILEGE_DROP_USER                   = "DROP_USER"
	OB_ORACLE_PRIVILEGE_CREATE_TYPE                 = "CREATE_TYPE"
	OB_ORACLE_PRIVILEGE_CREATE_ANY_TYPE             = "CREATE_ANY_TYPE"
	OB_ORACLE_PRIVILEGE_ALTER_ANY_TYPE              = "ALTER_ANY_TYPE"
	OB_ORACLE_PRIVILEGE_DROP_ANY_TYPE               = "DROP_ANY_TYPE"
	OB_ORACLE_PRIVILEGE_EXECUTE_ANY_TYPE            = "EXECUTE_ANY_TYPE"
	OB_ORACLE_PRIVILEGE_UNDER_ANY_TYPE              = "UNDER_ANY_TYPE"
	OB_ORACLE_PRIVILEGE_PURGE_DBA_RECYCLEBIN        = "PURGE_DBA_RECYCLEBIN"
	OB_ORACLE_PRIVILEGE_CREATE_ANY_OUTLINE          = "CREATE_ANY_OUTLINE"
	OB_ORACLE_PRIVILEGE_ALTER_ANY_OUTLINE           = "ALTER_ANY_OUTLINE"
	OB_ORACLE_PRIVILEGE_DROP_ANY_OUTLINE            = "DROP_ANY_OUTLINE"
	OB_ORACLE_PRIVILEGE_SYSKM                       = "SYSKM"
	OB_ORACLE_PRIVILEGE_CREATE_TABLESPACE           = "CREATE_TABLESPACE"
	OB_ORACLE_PRIVILEGE_ALTER_TABLESPACE            = "ALTER_TABLESPACE"
	OB_ORACLE_PRIVILEGE_DROP_TABLESPACE             = "DROP_TABLESPACE"
	OB_ORACLE_PRIVILEGE_SHOW_PROCESS                = "SHOW_PROCESS"
	OB_ORACLE_PRIVILEGE_ALTER_SYSTEM                = "ALTER_SYSTEM"
	OB_ORACLE_PRIVILEGE_CREATE_DATABASE_LINK        = "CREATE_DATABASE_LINK"
	OB_ORACLE_PRIVILEGE_CREATE_PUBLIC_DATABASE_LINK = "CREATE_PUBLIC_DATABASE_LINK"
	OB_ORACLE_PRIVILEGE_DROP_DATABASE_LINK          = "DROP_DATABASE_LINK"
	OB_ORACLE_PRIVILEGE_ALTER_SESSION               = "ALTER_SESSION"
	OB_ORACLE_PRIVILEGE_ALTER_DATABASE              = "ALTER_DATABASE"
	OB_ORACLE_PRIVILEGE_EXEMPT_REDACTION_POLICY     = "EXEMPT_REDACTION_POLICY"
	OB_ORACLE_PRIVILEGE_SYSDBA                      = "SYSDBA"
	OB_ORACLE_PRIVILEGE_SYSOPER                     = "SYSOPER"
	OB_ORACLE_PRIVILEGE_SYSBACKUP                   = "SYSBACKUP"
	OB_ORACLE_PRIVILEGE_CREATE_ANY_DIRECTORY        = "CREATE_ANY_DIRECTORY"
	OB_ORACLE_PRIVILEGE_DROP_ANY_DIRECTORY          = "DROP_ANY_DIRECTORY"
)

const (
	OB_CONNECTION_TYPE_DIRECT = "DIRECT"
	OB_CONNECTION_TYPE_PROXY  = "PROXY"
)

var OB_MYSQL_PRIVILEGES = []string{OB_MYSQL_PRIVILEGE_ALTER, OB_MYSQL_PRIVILEGE_CREATE, OB_MYSQL_PRIVILEGE_DELETE, OB_MYSQL_PRIVILEGE_DROP, OB_MYSQL_PRIVILEGE_INSERT, OB_MYSQL_PRIVILEGE_INDEX, OB_MYSQL_PRIVILEGE_SELECT, OB_MYSQL_PRIVILEGE_UPDATE, OB_MYSQL_PRIVILEGE_CREATE_VIEW, OB_MYSQL_PRIVILEGE_SHOW_VIEW, OB_MYSQL_PRIVILEGE_CREATE_USER, OB_MYSQL_PRIVILEGE_PROCESS, OB_MYSQL_PRIVILEGE_SUPER, OB_MYSQL_PRIVILEGE_SHOW_DATABASES, OB_MYSQL_PRIVILEGE_GRANT_OPTION}

var OB_ORACLE_PRIVILEGES = []string{
	OB_ORACLE_PRIVILEGE_CREATE_SESSION,
	OB_ORACLE_PRIVILEGE_CREATE_TABLE,
	OB_ORACLE_PRIVILEGE_CREATE_ANY_TABLE,
	OB_ORACLE_PRIVILEGE_ALTER_ANY_TABLE,
	OB_ORACLE_PRIVILEGE_BACKUP_ANY_TABLE,
	OB_ORACLE_PRIVILEGE_DROP_ANY_TABLE,
	OB_ORACLE_PRIVILEGE_LOCK_ANY_TABLE,
	OB_ORACLE_PRIVILEGE_COMMENT_ANY_TABLE,
	OB_ORACLE_PRIVILEGE_SELECT_ANY_TABLE,
	OB_ORACLE_PRIVILEGE_INSERT_ANY_TABLE,
	OB_ORACLE_PRIVILEGE_UPDATE_ANY_TABLE,
	OB_ORACLE_PRIVILEGE_DELETE_ANY_TABLE,
	OB_ORACLE_PRIVILEGE_FLASHBACK_ANY_TABLE,
	OB_ORACLE_PRIVILEGE_CREATE_ROLE,
	OB_ORACLE_PRIVILEGE_DROP_ANY_ROLE,
	OB_ORACLE_PRIVILEGE_GRANT_ANY_ROLE,
	OB_ORACLE_PRIVILEGE_ALTER_ANY_ROLE,
	OB_ORACLE_PRIVILEGE_AUDIT_ANY,
	OB_ORACLE_PRIVILEGE_GRANT_ANY_PRIVILEGE,
	OB_ORACLE_PRIVILEGE_GRANT_ANY_OBJECT_PRIVILEGE,
	OB_ORACLE_PRIVILEGE_CREATE_ANY_INDEX,
	OB_ORACLE_PRIVILEGE_ALTER_ANY_INDEX,
	OB_ORACLE_PRIVILEGE_DROP_ANY_INDEX,
	OB_ORACLE_PRIVILEGE_CREATE_ANY_VIEW,
	OB_ORACLE_PRIVILEGE_DROP_ANY_VIEW,
	OB_ORACLE_PRIVILEGE_CREATE_VIEW,
	OB_ORACLE_PRIVILEGE_SELECT_ANY_DICTIONARY,
	OB_ORACLE_PRIVILEGE_CREATE_PROCEDURE,
	OB_ORACLE_PRIVILEGE_CREATE_ANY_PROCEDURE,
	OB_ORACLE_PRIVILEGE_ALTER_ANY_PROCEDURE,
	OB_ORACLE_PRIVILEGE_DROP_ANY_PROCEDURE,
	OB_ORACLE_PRIVILEGE_EXECUTE_ANY_PROCEDURE,
	OB_ORACLE_PRIVILEGE_CREATE_SYNONYM,
	OB_ORACLE_PRIVILEGE_CREATE_ANY_SYNONYM,
	OB_ORACLE_PRIVILEGE_DROP_ANY_SYNONYM,
	OB_ORACLE_PRIVILEGE_CREATE_PUBLIC_SYNONYM,
	OB_ORACLE_PRIVILEGE_DROP_PUBLIC_SYNONYM,
	OB_ORACLE_PRIVILEGE_CREATE_SEQUENCE,
	OB_ORACLE_PRIVILEGE_CREATE_ANY_SEQUENCE,
	OB_ORACLE_PRIVILEGE_ALTER_ANY_SEQUENCE,
	OB_ORACLE_PRIVILEGE_DROP_ANY_SEQUENCE,
	OB_ORACLE_PRIVILEGE_SELECT_ANY_SEQUENCE,
	OB_ORACLE_PRIVILEGE_CREATE_TRIGGER,
	OB_ORACLE_PRIVILEGE_CREATE_ANY_TRIGGER,
	OB_ORACLE_PRIVILEGE_ALTER_ANY_TRIGGER,
	OB_ORACLE_PRIVILEGE_DROP_ANY_TRIGGER,
	OB_ORACLE_PRIVILEGE_CREATE_PROFILE,
	OB_ORACLE_PRIVILEGE_ALTER_PROFILE,
	OB_ORACLE_PRIVILEGE_DROP_PROFILE,
	OB_ORACLE_PRIVILEGE_CREATE_USER,
	OB_ORACLE_PRIVILEGE_BECOME_USER,
	OB_ORACLE_PRIVILEGE_ALTER_USER,
	OB_ORACLE_PRIVILEGE_DROP_USER,
	OB_ORACLE_PRIVILEGE_CREATE_TYPE,
	OB_ORACLE_PRIVILEGE_CREATE_ANY_TYPE,
	OB_ORACLE_PRIVILEGE_ALTER_ANY_TYPE,
	OB_ORACLE_PRIVILEGE_DROP_ANY_TYPE,
	OB_ORACLE_PRIVILEGE_EXECUTE_ANY_TYPE,
	OB_ORACLE_PRIVILEGE_UNDER_ANY_TYPE,
	OB_ORACLE_PRIVILEGE_PURGE_DBA_RECYCLEBIN,
	OB_ORACLE_PRIVILEGE_CREATE_ANY_OUTLINE,
	OB_ORACLE_PRIVILEGE_ALTER_ANY_OUTLINE,
	OB_ORACLE_PRIVILEGE_DROP_ANY_OUTLINE,
	OB_ORACLE_PRIVILEGE_SYSKM,
	OB_ORACLE_PRIVILEGE_CREATE_TABLESPACE,
	OB_ORACLE_PRIVILEGE_ALTER_TABLESPACE,
	OB_ORACLE_PRIVILEGE_DROP_TABLESPACE,
	OB_ORACLE_PRIVILEGE_SHOW_PROCESS,
	OB_ORACLE_PRIVILEGE_ALTER_SYSTEM,
	OB_ORACLE_PRIVILEGE_CREATE_DATABASE_LINK,
	OB_ORACLE_PRIVILEGE_CREATE_PUBLIC_DATABASE_LINK,
	OB_ORACLE_PRIVILEGE_DROP_DATABASE_LINK,
	OB_ORACLE_PRIVILEGE_ALTER_SESSION,
	OB_ORACLE_PRIVILEGE_ALTER_DATABASE,
	OB_ORACLE_PRIVILEGE_EXEMPT_REDACTION_POLICY,
	OB_ORACLE_PRIVILEGE_SYSDBA,
	OB_ORACLE_PRIVILEGE_SYSOPER,
	OB_ORACLE_PRIVILEGE_SYSBACKUP,
	OB_ORACLE_PRIVILEGE_CREATE_ANY_DIRECTORY,
	OB_ORACLE_PRIVILEGE_DROP_ANY_DIRECTORY,
}

const (
	DB_OCEANBASE = "oceanbase"
	DB_OCS       = "ocs"

	DEFAULT_HOST = "%"

	SYS_USER_PROXYRO = "proxyro"

	CONFIG_RPC_PORT   = "rpc_port"
	CONFIG_MYSQL_PORT = "mysql_port"

	DEFAULT_MYSQL_PORT = 2881
	DEFAULT_RPC_PORT   = 2882

	CONFIG_HOME_PATH      = "homePath"
	CONFIG_ROOT_PWD       = "rootPwd"
	CONFIG_AGENT_PASSWORD = "agentRootPwd"
	CONFIG_DATA_DIR       = "data_dir"
	CONFIG_REDO_DIR       = "redo_dir"
	CONFIG_CLOG_DIR       = "clog_dir"
	CONFIG_SLOG_DIR       = "slog_dir"

	CONFIG_LOCAL_IP  = "local_ip"
	CONFIG_DEV_NAME  = "devname"
	CONFIG_LOG_LEVEL = "syslog_level"
	CONFIG_ZONE      = "zone"

	CONFIG_ROOT_PASSWORD = "rootPwd"
	CONFIG_RS_LIST       = "rootservice_list"
	CONFIG_CLUSTER_ID    = "cluster_id"
	CONFIG_CLUSTER_NAME  = "cluster"

	CONFIG_FILE_LOCAL_IP = "local_ip"

	OB_PARAM_CLUSTER_ID   = "cluster_id"
	OB_PARAM_CLUSTER_NAME = "cluster"

	// configurable dir
	OB_DIR_STORE = "store"
	OB_DIR_CLOG  = "clog"
	OB_DIR_SLOG  = "slog"

	// unconfigurable dir
	OB_DIR_ETC     = "etc"
	OB_DIR_LOG     = "log"
	OB_DIR_SSTABLE = "store/sstable"

	OB_CONFIG_FILE = "observer.config.bin"
	OB_ADMIN       = "ob_admin"
	OB_BLOCK_FILE  = "block_file"

	OB_IMPORT_TIME_ZONE_INFO_SCRIPT = "import_time_zone_info.py"
	OB_IMPORT_SRS_DATA_SCRIPT       = "import_srs_data.py"
	OB_IMPORT_TIME_ZONE_INFO_FILE   = "timezone_V1.log"
	OB_IMPORT_SRS_DATA_FILE         = "default_srs_data_mysql.sql"

	OB_MODULE_TIMEZONE = "timezone"
	OB_MODULE_GIS      = "gis"
	OB_MODULE_REDIS    = "redis"

	// env
	OB_ROOT_PASSWORD = "OB_ROOT_PASSWORD"

	OB_VERSION_4_3_5_2 = "4.3.5.2"
)

const (
	CHUNK_SIZE uint64 = 1024*1024*8 - 1
)

const (
	TICK_INTERVAL_FOR_OB_STATUS_CHECK = 5 * time.Second
	TICK_NUM_FOR_OB_STATUS_CHECK      = 60

	OBSERVER_STATUS_DELETING = "DELETING"
)

const (
	USERNAME_PATTERN    = "^[a-zA-Z][a-zA-Z_0-9]{1,29}$"
	ROLE_PATTERN        = "^[a-zA-Z][a-zA-Z0-9_]{0,30}[a-zA-Z0-9]$"
	DATABASE_PATTERN    = "^[a-zA-Z_0-9-]{2,64}$"
	TENANT_NAME_PATTERN = "^[a-zA-Z0-9-_~#+]+$"
)

var PATH_PARAM_PATTERN = map[string]string{
	URI_PARAM_USER:     USERNAME_PATTERN,
	URI_PARAM_ROLE:     ROLE_PATTERN,
	URI_PARAM_DATABASE: DATABASE_PATTERN,
	URI_PARAM_NAME:     TENANT_NAME_PATTERN,
}
